
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dvd_rental'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'dvd_rental'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
  dvd_rental:
    # Staging models - materialized as views for lightweight transformations
    staging:
      +materialized: view
      +tags: ['staging']
    
    # Mart models - materialized as tables for performance
    marts:
      +materialized: table
      +tags: ['mart']
      
      # Dimensions
      dim_customer:
        +tags: ['dimension', 'mart']
      dim_film:
        +tags: ['dimension', 'mart']
      dim_store:
        +tags: ['dimension', 'mart']
      dim_date:
        +tags: ['dimension', 'mart']
      
      # Facts
      fct_rental:
        +tags: ['fact', 'mart']
      
      # BI / Analytics
      rental_analytics:
        +tags: ['bi', 'analytics', 'mart']
        +description: "Final denormalized table for BI consumption"
