dvd_rental:
  target: dev
  outputs:
    dev:
      type: databricks
      catalog: workspace
      schema: dvd_rental
      host: "{{ env_var('DATABRICKS_HOST') }}"
      http_path: "{{ env_var('DATABRICKS_HTTP_PATH') }}"
      token: "{{ env_var('DATABRICKS_TOKEN') }}"
      threads: 12

